export { Hero } from './components/Hero'
export { Header } from './components/Header'
export { CustomCursor } from './components/CustomCursor'
export { Problema } from './components/Problema'
export { FasesCuidado } from './components/FasesCuidado'
export { Pilares } from './components/Pilares'
export { ManualSection } from './components/ManualSection'
export { ParaQuem, Depoimento } from './components/ParaQuem'
export { QuemSomos } from './components/QuemSomos'
export { Servicos } from './components/Servicos'
export { CTAFinal } from './components/CTAFinal'
export { Footer } from './components/Footer'
